name = "TrihpFEM"
uuid = "6f95704f-31d0-4cfb-aa9d-6d40374f9d53"
version = "0.1.0"
authors = ["Ignacio Ojea <iojea@dm.uba.ar>"]

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
ExactPredicates = "429591f6-91af-11e9-00e2-59fbe8cec110"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"

[compat]
Aqua = "0.8.14"
CommonSolve = "0.2.6"
Dictionaries = "0.4.6"
DocStringExtensions = "0.9.5"
EllipsisNotation = "1.8.0"
ExactPredicates = "2.2.9"
FixedSizeArrays = "1.2.0"
LinearAlgebra = "1.12.0"
Makie = "0.24.8"
Markdown = "1.11.0"
Pkg = "1.12.1"
Polynomials = "4.1.0"
Printf = "1.11.0"
SparseArrays = "1.12.0"
StaticArrays = "1.9.15"
TensorCast = "0.4.9"
TensorOperations = "5.3.1"
Test = "1.11.0"
Triangulate = "3.0.0"
julia = "1.12"
